# Generated by Django 5.1.7 on 2025-03-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_youtube',
        ),
    ]
