# Generated by Django 5.1.7 on 2025-03-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_social_youtube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='desription',
            new_name='description',
        ),
    ]
