# Generated by Django 5.1.7 on 2025-03-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_desription_skill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_image',
            field=models.ImageField(blank=True, default='profiles/panda.png', null=True, upload_to='profiles/'),
        ),
    ]
